name: Build PCBs

on:
  workflow_call:
  push:
#    paths:
#    - "*.kicad_sch"
#    - "*.kicad_pcb"
#    - "*.kicad_pro"
#    - "kibot.yml"
  pull_request:
#    paths:
#    - "*.kicad_sch"
#    - "*.kicad_pcb"
#    - "*.kicad_pro"
#    - "kibot.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: INTI-CMNB/KiBot@v2_k9
        with:
          config: kibot.yml
          dir: output
          schema: 'FACET.kicad_sch'
          board: 'FACET.kicad_pcb'

      - name: upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - id: deployment
        if: github.ref_name == 'main'
        uses: actions/deploy-pages@v4