name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_pcb:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_pcbs.yml@main

  release:
    runs-on: ubuntu-latest
    needs: [build_pcb]
    if: success()
    environment:
      name: github-pages
      url: ${{ steps.release.outputs.page_url }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - id: deployment
        if: github.ref_name == 'main'
        uses: actions/deploy-pages@v4