name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pcb:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_pcbs.yml@main

  firmware:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_stm32_fw.yml@main

  release:
    runs-on: ubuntu-latest
    needs: [pcb,firmware]
    if: success()
    environment:
      name: github-pages
      url: ${{ steps.release.outputs.page_url }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
      - name: Zip up release artifact
        run: 7z a aspect2-pcb-${{ github.ref_name }}.7z *
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: aspect2-pcb-*.7z

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - id: deployment
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/deploy-pages@v4