name: Release

on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pcb:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_pcbs.yml@rc1

  firmware:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_stm32_fw.yml@rc1

  release:
    runs-on: ubuntu-latest
    needs: [pcb,firmware]
    if: success()
    environment:
      name: github-pages
      url: ${{ steps.release.outputs.page_url }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
      - name: Zip up release artifact
        run: 7z a aspect2-pcb-${{ github.ref_name }}.7z *

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'output'

      - id: deployment
        if: github.ref_name == 'rc1'
        uses: actions/deploy-pages@v4
