name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*"
      
jobs:
  build_pcb:
    uses: xboxoneresearch/ASPECT2-PCB/.github/workflows/build_pcbs.yml@main

  release:
    runs-on: ubuntu-latest
    needs: [build_pcb]
    if: success()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
